const page = document.body.dataset.page;
let lang = 'en';

const pages = {
  about: {
    en: { label:'ABOUT INTRON', title:'A sharper link in<br>the global value chain.', intro:'INTRON GLOBAL is a global materials specialist supplying high-performance fibers, engineering plastics, functional additives and environmental engineering facilities.', lead:'We connect world-class material manufacturers with customers who need dependable performance, practical quality control and a competitive supply chain.', facts:[['RIGOROUS QC','Global quality control standard'],['TOP-TIER PARTNERS','OCF, Lotte Chem, Samyang EP, Formosa, Nan Ya and more'],['GLOBAL REACH','EU, UK, Turkey, Middle East and Korea']], sectionTitle:'The material partner<br>built for performance.', copy:'Our work begins with rigorous quality control and continues through reliable global sourcing. We support the full path from the right material selection to steady supply for customers at home and abroad.' },
    ko: { label:'회사소개', title:'글로벌 가치사슬을 잇는<br>더 정확한 연결.', intro:'인트론글로벌은 고성능 섬유, 엔지니어링 플라스틱, 기능성 첨가제 및 환경 엔지니어링 설비를 공급하는 글로벌 소재 전문기업입니다.', lead:'세계적인 소재 제조사와 성능·품질·안정적 공급을 필요로 하는 고객을 연결합니다.', facts:[['엄격한 품질관리','글로벌 품질관리 기준'],['최고 수준의 파트너','OCF, 롯데케미칼, 삼양EP, 포모사, 난야 등'],['글로벌 네트워크','EU, 영국, 튀르키예, 중동, 한국']], sectionTitle:'성능을 위해 움직이는<br>소재 파트너.', copy:'엄격한 품질관리로 시작해 신뢰할 수 있는 글로벌 소싱으로 이어갑니다. 국내외 고객이 필요한 소재 선정부터 안정적 공급까지 전 과정을 지원합니다.' }
  },
  materials: {
    en: { label:'MATERIAL PORTFOLIO', title:'Materials for every<br>critical performance.', intro:'A single view of the advanced materials and engineering solutions INTRON GLOBAL trades and supplies.', groups:[
      ['01','GLASS & CARBON FIBERS','High-strength reinforcement materials for engineering plastics and composites.',['OCF glass fiber chopped strands made in Korea','Carbon fiber chopped strands for thermoplastics','OCF quality control technology and FTA certified export']],
      ['02','ENGINEERING RESINS','Base, specialty and recycled resin choices for demanding applications.',['PA, PP, PC, POM and EVA','Liquid & solid epoxy resins and HHPA curing agent','Medical & food-contact PC, PC/ABS alloy','rPC, rPA6/66, rPBT, rABS, rASA, PCR & PIR']],
      ['03','PERFORMANCE ADDITIVES','Made-in-Korea customisation and globally sourced enhancement.',['Custom masterbatch from Woosung Chemical','Impact modifiers from Formosa and LG Chem','Songwon antioxidants and UV stabilizers','PFAS-free heat stabilizers and anti-dripping agent']],
      ['04','WATER TREATMENT ENGINEERING','Precision components made for corrosive, underwater environments.',['High-durability water treatment frame cassettes','Custom industrial water treatment components','Corrosion resistance, structural stability and long lifecycle']]
    ], afterTitle:'One portfolio.<br>Practical solutions.', after:'Every solution is supported by quality-led sourcing, responsive technical communication and supply-chain know-how.' },
    ko: { label:'소재 포트폴리오', title:'중요한 성능을 위한<br>모든 소재.', intro:'인트론글로벌이 공급·유통하는 첨단 소재와 엔지니어링 솔루션을 한곳에 정리했습니다.', groups:[
      ['01','유리섬유 & 탄소섬유','엔지니어링 플라스틱과 복합소재용 고강도 보강 소재.',['국내 생산 OCF 유리섬유 촙드 스트랜드','열가소성 수지용 탄소섬유 촙드 스트랜드','OCF 품질관리 기술 및 FTA 인증 수출']],
      ['02','엔지니어링 레진','고성능 애플리케이션을 위한 범용·특수·재생 레진.',['PA, PP, PC, POM 및 EVA','액상·고상 에폭시 레진 및 HHPA 경화제','의료·식품 접촉용 PC, PC/ABS 알로이','rPC, rPA6/66, rPBT, rABS, rASA, PCR & PIR']],
      ['03','기능성 첨가제','국내 맞춤 생산과 글로벌 소싱 기반의 물성 개선 솔루션.',['우성케미칼 맞춤형 마스터배치','포모사·LG화학 충격보강제','송원 산화방지제 및 UV 안정제','PFAS-free 열안정제 및 난연 보조제']],
      ['04','수처리 엔지니어링','부식성과 수중 환경에 대응하는 정밀 엔지니어링 부품.',['고내구성 수처리용 프레임 카세트','맞춤형 산업용 수처리 부품','내식성, 구조적 안정성 및 긴 수명']]
    ], afterTitle:'하나의 포트폴리오.<br>실질적인 해답.', after:'모든 솔루션은 품질 중심의 소싱, 빠른 기술 커뮤니케이션, 안정적인 공급망 노하우를 기반으로 합니다.' }
  },
  contact: {
    en: { label:'CONTACT', title:'Let’s discuss what<br>comes next.', intro:'For material sourcing, distribution and engineering inquiries, contact INTRON GLOBAL.', cards:[['EMAIL','intron1101@gmail.com'],['FAX','0504-423-5748'],['ADDRESS','503-439, 9 Gangnam-ro, Giheung-gu,<br>Yongin-si, Gyeonggi-do, Korea']], helper:'Please include your company, required material and application so we can respond with the right solution.', button:'Send an email <span>↗</span>' },
    ko: { label:'문의하기', title:'다음 거래를<br>함께 논의하세요.', intro:'소재 소싱, 유통 및 엔지니어링 관련 문의는 인트론글로벌로 연락해 주세요.', cards:[['이메일','intron1101@gmail.com'],['팩스','0504-423-5748'],['주소','경기도 용인시 기흥구 강남로 9,<br>503-439호 (구갈동, 태평양프라자)']], helper:'회사명, 필요한 소재와 적용 용도를 함께 알려주시면 더 정확하게 안내해 드립니다.', button:'이메일 문의하기 <span>↗</span>' }
  }
};

function nav(d) {
  return `<header class="header sub-header"><a class="brand" href="index.html"><img class="brand-logo brand-logo-dark" src="assets/intron-logo-vertical-black.jpeg" alt="INTRON logo"><span class="brand-wordmark"><b>INTRON</b><small>GLOBAL</small></span></a><nav class="nav"><a href="about.html">${d.navAbout}</a><a href="materials.html">${d.navMaterials}</a><a href="index.html#network">${d.navNetwork}</a><a href="contact.html">${d.navContact}</a></nav><div class="header-actions"><button class="language-toggle" type="button" aria-label="Change language"><span class="${lang === 'en' ? 'active' : ''}">EN</span><span>/</span><span class="${lang === 'ko' ? 'active' : ''}">KR</span></button><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false"><span></span><span></span></button></div></header>`;
}

function footer(d) {
  const footerCta = page === 'contact' ? '' : `<div class="footer-top"><div><p class="eyebrow light">${d.footerEyebrow}</p><h2>${d.footerTitle}</h2></div><a class="button button-primary" href="contact.html">${d.footerButton} <span>↗</span></a></div>`;
  return `<footer class="footer footer-rich" id="footer-contact">${footerCta}<div class="footer-bottom"><a class="brand footer-brand" href="index.html"><img class="brand-logo brand-logo-light" src="assets/intron-logo-white.png" alt="INTRON logo"><span class="brand-wordmark"><b>INTRON</b><small>GLOBAL</small></span></a><div class="footer-company"><strong>INTRON GLOBAL CO., LTD.</strong><br>${d.footerBusiness}<br>${d.footerAddress}</div><div class="footer-contact"><a href="mailto:intron1101@gmail.com">intron1101@gmail.com</a><br>FAX. 0504-423-5748<br>© ${new Date().getFullYear()} INTRON GLOBAL CO., LTD.</div><a href="#top" class="to-top">${d.toTop}</a></div></footer>`;
}

function render() {
  const common = lang === 'en' ? { navAbout:'About',navMaterials:'Materials',navNetwork:'Network',navContact:'Contact',footerEyebrow:'CONTACT',footerTitle:'Take the next step<br>with INTRON GLOBAL.',footerButton:'Contact us',footerBusiness:'Wholesale · Trade · Export / Import',footerAddress:'503-439, 9 Gangnam-ro, Giheung-gu, Yongin-si, Gyeonggi-do, Korea',toTop:'BACK TO TOP ↑' } : { navAbout:'회사소개',navMaterials:'소재 포트폴리오',navNetwork:'글로벌 네트워크',navContact:'문의',footerEyebrow:'문의하기',footerTitle:'인트론글로벌과 함께<br>다음 단계를 시작하세요.',footerButton:'거래 문의하기',footerBusiness:'사업분야: 도매업 · 무역업(수출·수입)',footerAddress:'경기도 용인시 기흥구 강남로 9, 503-439호 (구갈동, 태평양프라자)',toTop:'맨 위로 ↑' };
  const d = pages[page][lang];
  const content = page === 'materials' ? `<section class="sub-content portfolio-grid">${d.groups.map(g => `<article class="portfolio-card"><span>${g[0]}</span><p class="eyebrow">${g[1]}</p><h2>${g[2]}</h2><ul>${g[3].map(i=>`<li>${i}</li>`).join('')}</ul></article>`).join('')}</section><section class="sub-closing"><p class="eyebrow">INTRON GLOBAL</p><h2>${d.afterTitle}</h2><p>${d.after}</p><a class="button button-primary" href="contact.html">${common.footerButton} <span>↗</span></a></section>` : page === 'contact' ? `<section class="sub-content contact-page"><p class="contact-helper">${d.helper}</p><div class="contact-page-cards">${d.cards.map((c,i)=>`<article><span>${c[0]}</span>${i === 0 ? `<a href="mailto:${c[1]}">${c[1]}</a>` : `<p>${c[1]}</p>`}</article>`).join('')}</div><a class="button button-primary" href="mailto:intron1101@gmail.com">${d.button}</a></section>` : `<section class="sub-content about-page"><p class="about-page-lead">${d.lead}</p><div class="fact-grid">${d.facts.map((f,i)=>`<article><span>0${i+1}</span><h3>${f[0]}</h3><p>${f[1]}</p></article>`).join('')}</div><div class="about-statement"><p class="eyebrow">INTRON GLOBAL</p><h2>${d.sectionTitle}</h2><p>${d.copy}</p><a class="button button-primary" href="materials.html">${common.navMaterials} <span>↗</span></a></div></section>`;
  document.documentElement.lang = lang;
  document.title = `${page === 'about' ? common.navAbout : page === 'materials' ? common.navMaterials : common.navContact} | INTRON GLOBAL`;
  document.getElementById('app').innerHTML = `<div class="site-shell sub-shell" id="top">${nav(common)}<main><section class="sub-hero"><div><p class="eyebrow light">${d.label}</p><h1>${d.title}</h1><p>${d.intro}</p></div><span class="sub-page-index">0${['about','materials','contact'].indexOf(page)+1}</span></section>${content}</main>${footer(common)}</div>`;
  document.querySelector('.language-toggle').addEventListener('click', () => { lang = lang === 'en' ? 'ko' : 'en'; render(); });
  const menu = document.querySelector('.menu-toggle'); const menuNav = document.querySelector('.nav');
  menu.addEventListener('click', () => { const open = menuNav.classList.toggle('open'); menu.setAttribute('aria-expanded', open); });
  if (page === 'contact') renderInquiryForm(lang);
}
render();

function renderInquiryForm(locale) {
  const formCopy = locale === 'ko' ? {company:'회사명',companyHint:'회사명을 입력해 주세요',name:'담당자명',nameHint:'성함을 입력해 주세요',message:'문의 내용',messageHint:'문의하실 내용을 입력해 주세요',attachment:'첨부파일',attachmentHint:'선택 사항 · 최대 20MB · PDF, Office, TXT, JPG, PNG',notice:'문의 접수 후 확인하여 회신드립니다.',send:'문의 보내기 <span>↗</span>'} : {company:'COMPANY',companyHint:'Your company',name:'NAME',nameHint:'Your name',message:'MESSAGE',messageHint:'Tell us about your inquiry',attachment:'ATTACHMENT',attachmentHint:'Optional · Up to 20MB · PDF, Office, TXT, JPG, PNG',notice:'We will review your inquiry and respond by email.',send:'Send inquiry <span>↗</span>'};
  const target = document.querySelector('.contact-page');
  target.innerHTML = `<form class="form inquiry-form"><div class="field"><label>${formCopy.company}</label><input name="company" required placeholder="${formCopy.companyHint}"></div><div class="field"><label>${formCopy.name}</label><input name="name" required placeholder="${formCopy.nameHint}"></div><div class="field full"><label>EMAIL</label><input name="email" required type="email" placeholder="email@company.com"></div><div class="field full"><label>${formCopy.message}</label><textarea name="message" required placeholder="${formCopy.messageHint}"></textarea></div><div class="field full attachment-field"><label>${formCopy.attachment}</label><input id="attachment" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.txt,.jpg,.jpeg,.png"><small class="attachment-hint">${formCopy.attachmentHint}</small><span class="attachment-status" aria-live="polite"></span></div><p class="notice">${formCopy.notice}</p><button class="button button-primary" type="submit">${formCopy.send}</button></form>`;
  const form = target.querySelector('.inquiry-form'); const attachment = form.querySelector('#attachment'); const status = form.querySelector('.attachment-status');
  const allowed = ['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/jpeg','image/png','text/plain'];
  const t = (ko,en) => locale === 'ko' ? ko : en;
  attachment.addEventListener('change', () => { const file = attachment.files[0]; if (!file) { status.textContent = ''; return; } if (file.size > 20 * 1024 * 1024) { attachment.value = ''; status.textContent = t('파일은 20MB 이하만 첨부할 수 있습니다.','Files must be 20MB or smaller.'); return; } if (!allowed.includes(file.type)) { attachment.value = ''; status.textContent = t('지원하지 않는 파일 형식입니다.','This file type is not supported.'); return; } status.textContent = `${t('선택된 파일:','Selected file:')} ${file.name} (${Math.round(file.size/1024)} KB)`; });
  const honeypot = document.createElement('input'); honeypot.type = 'text'; honeypot.name = 'hp_field'; honeypot.autocomplete = 'off'; honeypot.tabIndex = -1; honeypot.setAttribute('aria-hidden','true'); honeypot.className = 'honeypot'; form.append(honeypot);
  form.addEventListener('submit', async (event) => { event.preventDefault(); if (honeypot.value.trim()) return; const company=form.elements.company.value.trim(), name=form.elements.name.value.trim(), email=form.elements.email.value.trim(), message=form.elements.message.value.trim(), button=form.querySelector('button'); if (message.length < 20) return alert(t('문의 내용은 20자 이상 입력해 주세요.','Please enter at least 20 characters in your message.')); const prior=JSON.parse(localStorage.getItem('intron_contact_history') || '{}'), now=Date.now(); if (now-Number(prior.sentAt||0) < 60000) return alert(t('연속 전송은 60초 후에 다시 시도해 주세요.','Please wait 60 seconds before sending another inquiry.')); const original=button.innerHTML; button.disabled=true; button.textContent=t('전송 중...','Sending...'); try { let attachmentUrl=''; const file=attachment.files[0]; if(file){ status.textContent=t('첨부파일 업로드 중...','Uploading attachment...'); const body=new FormData(); body.append('file',file); const response=await fetch('https://file.io',{method:'POST',body}); const data=await response.json(); if(!data.link) throw new Error('Attachment upload failed'); attachmentUrl=data.link; } if(!window.emailjs) await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/emailjs-com@3/dist/email.min.js';script.onload=resolve;script.onerror=reject;document.head.append(script);}); window.emailjs.init('S_pZX4esOTmL2yED9'); await window.emailjs.send('INTRON MAIL','template_ahovfta',{name,email,subject:`${t('홈페이지 문의','Website inquiry')} | ${company}`,message,attachment_url:attachmentUrl}); localStorage.setItem('intron_contact_history',JSON.stringify({sentAt:now})); form.reset(); status.textContent=''; alert(t('문의가 정상적으로 전송되었습니다.','Your inquiry has been sent.')); } catch(error) { console.error(error); alert(t('전송에 실패했습니다. 잠시 후 다시 시도해 주세요.','Sending failed. Please try again shortly.')); } finally { button.disabled=false; button.innerHTML=original; } });
}
